### PR TITLE
fix: match glob logic for unignore ignores

### LINKED ISSUE #114: "Test matching with filepath..." not working with unignore glob pattern
If I have this in my `.gitignore`:
```gitignore
.vscode/*
!.vscode/settings.json
!.vscode/extensions.json
```

It seems that all the project files are ignored (as shown below), nothing will show up if you type any surely included filepath to "Test matching with filepath...":

Image

I am not creating a minimal replication here because you can easily replicate with https://github.com/antfu/eslint-config by simply adding below content to `.gitignore` and run `npx @eslint/config-inspector@0.6.0`

```gitignore
.vscode/*
!.vscode/settings.json
!.vscode/extensions.json
```

### PR DESCRIPTION
**Pull request by yidingww**
fix #114 

**The logic of `getMatchedGlobs` needs to be updated:**

If an unignore glob is matched, and if this glob without the `!` matches any previous ignore globs, all these globs should be unmatched.

### CODE REVIEW

File: shared/configs.ts [hunk 1]
```diff
@@ -13,9 +13,27 @@ function minimatch(file: string, pattern: string) {
...
+        const unignoreMatched = getMatchedGlobs(file, flatGlobs.slice(0, i))
+        unmatched = unmatched.concat(unignoreMatched.length > 0 ? unignoreMatched : [], glob)
+      }
+      else {
+        unmatched.push(glob)
+      }
+    }
+  })
+
+  return flatGlobs.filter(glob => !unmatched.includes(glob))
```
Comment (antfu) [inline shared/configs.ts:36]: I guess the order of ignore and unignore might matter how it work. For the must accurate result, we might need to vendor ESLint's walker here: https://github.com/eslint/eslint/blob/5db226f4da9ad7d53a4505a90290b68d4036c082/lib/eslint/eslint-helpers.js#L216

Comment (yidingww) [reply shared/configs.ts]: @antfu I just updated the PR

I took a different approach, cos i realised that `@eslint/config-array` has a very convenient `isFileIgnored` [here](https://github.com/eslint/rewrite/tree/main/packages/config-array#determining-ignored-paths), we can use this to decide if a file is ignored, and that should fix the issue entirely.

I don't think we need to vendor the eslint-helper since it's not exported and there are a long chain of dependencies in eslint's implementations.

File: shared/configs.ts [hunk 2]
```diff
@@ -38,31 +39,47 @@ export function isGeneralConfig(config: FlatConfigItem) {
...
       result.configs.push(index)
-    result.globs.push(
-      ...positive,
-      ...negative,
-    )
+      // push positive globs only when there are configs matched
+      result.globs.push(...positive)
+    }
+    // push negative globs except for unignore globs
+    result.globs.push(...negative.filter(glob => !glob.startsWith('!')))
```
Comment (comp615) [inline shared/configs.ts:59]: I think you might also want to push negative unignore globs here, basically all matched globs. There's a [comment here](https://github.com/eslint/config-inspector/pull/109#discussion_r1873446942) where I made that switch, and I think including them causes the UI to be more clear to the user since it indicates that the globs matched, and the user can then interpret the "matched-unignore" (vs the unclear/inconsistent greyed out ui that implies it didn't match glob-wise)

File: shared/configs.ts [hunk 3]
```diff
@@ -48,17 +48,32 @@ export function matchFile(
...
   configs.forEach((config, index) => {
+    const isFileGlobalIgnored = configArray.isFileIgnored(filepath)
+    let isFileIgnoredInCurrConfig = false
+    if (config.ignores) {
+      const ignoreConfigArray = buildConfigArray([{
+        index: config.index,
+        // only include ignores because of how ConfigArray works internally:
+        // isFileIgnored only works when only `ignore` exists
+        // (https://github.com/eslint/rewrite/blob/config-array-v0.19.1/packages/config-array/src/config-array.js#L726)
+        ignores: config.ignores ?? [],
```
Comment (yidingww) [inline shared/configs.ts:59]: @antfu @comp615 Hi guys, I just updated the PR again here in this commit

On a special note, here in particular, we need to check the current config as well to make sure the file is not ignored in current config. See inline code comment for more details

**Comment by comp615** [comment]
Fwiw, I also added tests that you could bring over if @antfu likes this
approach more. Would help make sure the functionality is identical too!

**Comment by yidingww** [comment]
@comp615 I cherry picked your commits over, and updated the solution again, now should be quite accurate

File: patches/@eslint__config-array@0.19.1.patch [hunk 4]
```diff
@@ -0,0 +1,26 @@
...
+diff --git a/dist/esm/index.js b/dist/esm/index.js
+index 1e68f33e3d641d856ab25b8206be085b6c205067..7dd46e0b8872078bba033ac75c79a9046020d589 100644
+--- a/dist/esm/index.js
++++ b/dist/esm/index.js
+@@ -221,7 +221,7 @@ const CONFIG_TYPES = new Set(["array", "function"]);
+  * Fields that are considered metadata and not part of the config object.
+  * @type {Set<string>}
+  */
+-const META_FIELDS = new Set(["name"]);
++const META_FIELDS = new Set(["name", "index"]);
```
Comment (yidingww) [inline patches/@eslint__config-array@0.19.1.patch:23]: The patch here is for `@eslint/config-array` to work as expected. Currently `@eslint/config-array` doesn't allow custome META_FIELDS so a patch is needed

**Comment by antfu** [comment]
Thanks for both of your hard works! @comp615 @yidingww 

This implementation looks more solid to me, @comp615 do you mind me taking this inside of #109? Or do you have any thing to add?

**Review by antfu — APPROVED** [review]

**Comment by comp615** [comment]
> Thanks for both of your hard works! @comp615 @yidingww
> 
> This implementation looks more solid to me, @comp615 do you mind me taking this inside of #109? Or do you have any thing to add?

Agree that using the actual config files is a more directly and reliable way to match. I don't know the history here, but I assume something like the metadata issue is why it wasn't done this way in the first place? Or perhaps because it seems duplicative to match, and then match globs again anyways.

I left a little bit of feedback to clean it up; if I were you, I'd just want to make sure that there's a path forward to removing the "patch" of config-array. But otherwise I think this is great!

File: shared/configs.ts [hunk 5]
```diff
@@ -15,7 +17,11 @@ function minimatch(file: string, pattern: string) {
 
 export function getMatchedGlobs(file: string, glob: (string | string[])[]) {
   const globs = (Array.isArray(glob) ? glob : [glob]).flat()
-  return globs.filter(glob => minimatch(file, glob)).flat()
+  return globs.filter((glob) => {
+    const matchResult = minimatch(file, glob)
+    // for unignore glob, we need to flip back the match
+    return glob.startsWith('!') ? !matchResult : matchResult
+  }).flat()
```
[the remark this answers is not in the document]
Comment (yidingww) [reply shared/configs.ts]: Good catch, just updated!

File: app/pages/configs.vue [hunk 6]
```diff
@@ -339,7 +339,7 @@ onMounted(async () => {
           <div>Ignored by globs:</div>
           <div flex="~ gap-2 items-center wrap">
             <GlobItem
-              v-for="glob, idx of fileMatchResult.globs"
+              v-for="glob, idx of fileMatchResult.globs.filter(glob => !glob.startsWith('!'))"
```
[the remark this answers is not in the document]
Comment (yidingww) [reply app/pages/configs.vue]: Turns out this filter was unnecessary anyway, I removed it in my latest commit

File: patches/@eslint__config-array@0.19.1.patch (hunk 4 above)
Comment (yidingww) [reply patches/@eslint__config-array@0.19.1.patch:23]: @comp615 Actually I kinda disagree that it's risky, isn't pnpm patch exactly for this kind of thing? The patch is against a specific version (as specified in package.json), so I don't see any risk here because the version is locked.

**Comment by yidingww** [comment]
> > Thanks for both of your hard works! @comp615 @yidingww
> > This implementation looks more solid to me, @comp615 do you mind me taking this inside of #109? Or do you have any thing to add?
> 
> Agree that using the actual config files is a more directly and reliable way to match. I don't know the history here, but I assume something like the metadata issue is why it wasn't done this way in the first place? Or perhaps because it seems duplicative to match, and then match globs again anyways.
> 
> I left a little bit of feedback to clean it up; if I were you, I'd just want to make sure that there's a path forward to removing the "patch" of config-array. But otherwise I think this is great!

@comp615 Thanks so much for the feedbacks! I replied all your comments and addressed the things you brought up. If all good, let's merge and release? @antfu 😁

**Review by antfu — APPROVED** [review]

File: patches/@eslint__config-array@0.19.1.patch (hunk 4 above)
Comment (comp615) [reply patches/@eslint__config-array@0.19.1.patch:23]: It's risky because it implies a divergence from the direction of the underlying library. It's equivalent to operating on a fork of a repo. Yes it will work, but it potentially creates issues down the road. What if it can't be patched the same way in the future? Or now the config-array update becomes potentially non-trivial. It's not immediate risk (it'll work)...it's strategic risk for the direction of each package.

that's why it's important to finish the discussion with the upstream author (maybe @antfu has a relationship there and can help)
